name: Download data and commit

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      # - name: Install dependencies
      #   run: |
      #     Rscript -e 'install.packages(c("dependencies-package1", "dependencies-package2"))'

      - name: Run R script
        run: |
          Rscript downloader.R

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Auto-commit: Add file from R script"
          git push
